name: Dependency Checks

on:
  schedule:
    - cron: "0 0 * * *"  # Every day
  workflow_dispatch: {}

env:
  JAVA_VERSION: '21'

jobs:
  dependency-check:
    name: Dependency Check
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Checkout GitHub Actions
      - uses: actions/checkout@v4
        with:
          repository: kestra-io/actions
          path: actions
          ref: main

      # Setup build
      - uses: ./actions/.github/actions/setup-build
        id: build
        with:
          java-enabled: true
          node-enabled: true
          caches-enabled: true

      # Run OWASP dependency check plugin
      - name: Gradle Dependency Check
        run: |
          ./gradlew dependencyCheckAggregate

      # Run Trivy image scan for Docker vulnerabilities, see https://github.com/aquasecurity/trivy
      - name: Docker Vulnerabilities Check
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: kestra/kestra:develop-full
          format: table
          skip-dirs: /app/plugins
          scanners: vuln